# .github/workflows/my-workflow.yml
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - name: confluence-markdown-sync
        uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: 'docs/README.md'
          to: '720109569'
          user: ${{ secrets.CONFLUENCE_USER }} 
          cloud: ${{ secrets.CONFLUENCE_CLOUD }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}

